// Copyright 2020 QMK / James Young (@noroadsleft)
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
#include "socd.h"
#include "veil60.h"
#include "config.h"


// LAYOUT macro is auto-generated by QMK from keyboard.json
// 71 keys total: Row 0: 14, Row 1: 15, Row 2: 13, Row 3: 16, Row 4: 13

enum custom_keycodes {
    ADC_PRINT = SAFE_RANGE,
    BOOT_KEY,
};

// Declare the helper implemented in veil60.c
extern void veil60_bootloader(void);

bool adc_printing_enabled = false;

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /*
     * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
     * │Esc│ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │ Backsp│
     * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
     * │ Tab │ Q │ W*│ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │  \  │
     * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
     * │ Caps │ A*│ S*│ D*│ F │ G │ H │ J │ K │ L │ ; │ ' │  Enter │
     * ├──────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬───┬───┤
     * │ Shift │ \ │ Z │ X │ C │ V │ B │ N │ M │ , │ . │Sft│ ↑ │ / │
     * ├────┬──┴─┬─┴──┬┴───┴───┴───┴───┴───┴───┼───┼───┼───┼───┼───┤
     * │Ctrl│Win │Alt │      Space      │Space2 │Sp3│Alt│Fn │Lft│Dwn│Rgt│
     * └────┴────┴────┴────────────────────────┴───┴───┴───┴───┴───┘
     * 
     * * = Hall Effect Sensor (WASD use direct keycode injection, bypassing matrix)
     */    
    [0] = LAYOUT(
        KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,
        KC_TAB,  KC_Q,    KC_NO,   KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
        KC_CAPS, KC_NO,   KC_NO,   KC_NO,   KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, KC_ENT,
        KC_LSFT, KC_BSLS, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_UP,  KC_RSFT,  KC_SLSH,
    KC_LCTL, KC_LGUI, KC_LALT, KC_F13,     KC_SPC,           KC_SPC,                    KC_RALT, MO(1),   KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
    ),
    /*
     * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
     * │ ` │F1 │F2 │F3 │F4 │F5 │F6 │F7 │F8 │F9 │F10│F11│F12│ Delete│
     * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
     * │     │   │   │   │   │   │   │   │   │   │   │PSn│SLk│Pause│
     * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
     * │      │AT │   │   │   │   │   │   │   │   │   │   │        │
     * ├──────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬───┬───┤
     * │       │   │   │   │   │   │   │   │   │   │   │   │PgU│   │
     * ├────┬──┴─┬─┴──┬┴───┴───┴───┴───┴───┴───┼───┼───┼───┼───┼───┤
     * │    │    │    │                 │       │   │   │mo2│Hom│PgD│End│
     * └────┴────┴────┴────────────────────────┴───┴───┴───┴───┴───┘
     * 
     * AT = ADC Toggle (for calibration)
     */ 
    [1] = LAYOUT(
        KC_GRV,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_DEL,
        _______, _______, _______, _______, _______, _______, _______, _______, KC_INS, _______, KC_PSCR, _______, _______, _______,
        _______, ADC_PRINT, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_PGUP, _______,
    QK_CLEAR_EEPROM, _______, _______, KC_TRNS, _______, _______, _______, MO(2),   KC_HOME, KC_PGDN, KC_END, _______, _______
    ),
    /*
     * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
     * │Clr│ADC│   │   │   │   │   │   │   │   │   │   │   │       │
     * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
     * │     │   │   │   │QBt│   │   │   │   │   │   │   │   │     │
     * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
     * │      │   │   │   │   │   │   │   │   │   │   │   │        │
     * ├──────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬───┬───┤
     * │       │   │   │   │   │   │   │   │   │   │   │   │   │   │
     * ├────┬──┴─┬─┴──┬┴───┴───┴───┴───┴───┴───┼───┼───┼───┼───┼───┤
     * │    │    │    │                 │       │   │   │   │   │   │   │
     * └────┴────┴────┴────────────────────────┴───┴───┴───┴───┴───┘
     */ 
    [2] = LAYOUT(
        QK_CLEAR_EEPROM, ADC_PRINT, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, 
    _______, _______, _______, _______, BOOT_KEY, _______, _______, _______, _______, _______, _______, _______, _______, _______, 
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
        _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______,
    _______, _______, _______, KC_TRNS, _______, _______, _______, _______, _______, _______, _______, _______, _______

    )
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case ADC_PRINT:
            if (record->event.pressed) {
                adc_printing_enabled = !adc_printing_enabled;
                uprintf("KEYMAP: ADC_PRINT toggled -> %s\n", adc_printing_enabled ? "ENABLED" : "DISABLED");
            }
        case 0x70E0:
            if (record->event.pressed) {
                adc_printing_enabled = !adc_printing_enabled;
                uprintf("KEYMAP: ADC_PRINT toggled -> %s\n", adc_printing_enabled ? "ENABLED" : "DISABLED");
            }
            return false;
        case 0xFFFF:
            if (record->event.pressed) {
                veil60_bootloader();
            }
            return false;
        case BOOT_KEY:
            if (record->event.pressed) {
                veil60_bootloader();
            }
            return false;
        
        // VIA custom keycode 0x7E0A (CUSTOM(0))
        case 0x7E0A:
            if (record->event.pressed) {
                adc_printing_enabled = !adc_printing_enabled;
                uprintf("VIA: ADC_PRINT toggled -> %s\n", adc_printing_enabled ? "ENABLED" : "DISABLED");
            }
            return false;
    }
    
    
    // Debug: log Enter and mechanical WASD presses from the matrix
    if (record->event.pressed) {
        if (keycode == KC_W) uprintf("KEYMAP: Mechanical W pressed\n");
        if (keycode == KC_A) uprintf("KEYMAP: Mechanical A pressed\n");
        if (keycode == KC_S) uprintf("KEYMAP: Mechanical S pressed\n");
        if (keycode == KC_D) uprintf("KEYMAP: Mechanical D pressed\n");
    }

    return true;
}
#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    // Ensure logical CCW => VOLD regardless of any global flip macro.

    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [1] = { ENCODER_CCW_CW(KC_MPRV, KC_MNXT) },
    [2] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
};
#endif

// Encoder switch handling (emulate matrix position KC_F13)
// Similar approach is used for WASD hall sensors - they bypass the matrix
// and use direct keycode injection via register_code/unregister_code
void matrix_scan_user(void) {
    static bool encoder_switch_pressed = false;
    static uint16_t encoder_debounce_timer = 0;
    static matrix_row_t prev_matrix[MATRIX_ROWS] = {0};
#ifdef ENCODER_BUTTON_PIN
    bool switch_state = !readPin(ENCODER_BUTTON_PIN);
    if (switch_state != encoder_switch_pressed) {
        // simple debounce
        if (timer_elapsed(encoder_debounce_timer) < 50) {
            // ignore spurious changes within 50ms
        } else {
            encoder_switch_pressed = switch_state;
            encoder_debounce_timer = timer_read();
            if (encoder_switch_pressed) {
                // emulate a normal matrix key at the unused spot so VIA can remap it
                tap_code(KC_MPLY);
            }
        }
    }
#endif

    // Temporary diagnostic: detect new matrix presses and print their row/col and mapped keycode
    for (uint8_t r = 0; r < MATRIX_ROWS; ++r) {
        matrix_row_t row_state = matrix_get_row(r);
        matrix_row_t new_presses = row_state & ~prev_matrix[r];
        if (new_presses) {
            // find each column pressed
            for (uint8_t c = 0; c < MATRIX_COLS; ++c) {
                if (new_presses & (1UL << c)) {
                    uint8_t layer = biton32(layer_state);
                    uint16_t kc = keymaps[layer][r][c];
                    uprintf("DIAG: new press r=%u c=%u layer=%u keycode=0x%04X\n", r, c, layer, kc);
                }
            }
        }
        prev_matrix[r] = row_state;
    }
}